apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: taskflow
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "postgres"
  JWT_SECRET: "mySecretKeyForJWTTokenGeneration2024TaskManagementPlatform"
  JWT_EXPIRY: "900000"
  JWT_REFRESH_EXPIRY: "604800000"
